version: '3.8'

services:
  python-mcp:
    build: 
      context: ./python
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"

  typescript-mcp:
    build:
      context: ./typescript
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: mcpuser
      POSTGRES_PASSWORD: mcppassword
      POSTGRES_DB: mcpdb
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  pgdata: