version: '3.8'

services:
  python-mcp:
    build: 
      context: ./python
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PYTHON_MCP_PORT:-3009}:3009"
    environment:
      - MCP_API_KEY=${MCP_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - COOLIFY_BASE_URL=${COOLIFY_BASE_URL}
      - COOLIFY_API_TOKEN=${COOLIFY_API_TOKEN}

  typescript-mcp:
    build:
      context: ./typescript
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${TYPESCRIPT_MCP_PORT:-3010}:3010"
    environment:
      - MCP_API_KEY=${MCP_API_KEY}
      - NODE_ENV=production